### ISSUE TITLE
asteroids deluxe mra not working

### ISSUE THREAD

**Issue by f3bandit** [obsidian-dot-dev/openFPGA-asteroidsdeluxe#1]
I attempted to generate the rom with the mra file but it did nothing. a window opened and closed but no rom file was created.
all you other rom files worked just fine. thx

**Comment by obsidian-dot-dev** [comment]
Can you run mra from the command-line with the "-v" option and check that the CRCs and MD5s match?  I just double-checked and it worked for me with what's in the repo (using the linux version of the mra tools).

**Comment by f3bandit** [comment]
It's fixed now, I ran pupudate on my analogue paokcet and it generated the rom
